version = 1

[[annotations]]
path = [
 ".formatter.exs",
 ".github/CODEOWNERS",
 ".gitignore",
 "CHANGELOG.md",
 "nerves_defconfig",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock",
 "VERSION"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Frank Hunleth"
SPDX-License-Identifier = "CC-BY-4.0"

# Buildroot derived or related files
# NOTE: packages here proactively have copyright assigned to the Buildroot
# developers to avoid worrying about copyright assignment when upstreaming.
[[annotations]]
path = [
 "Config.in",
 "package/**",
 "external.mk",
 "post-build.sh",
 "post-createfs.sh"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "The Buildroot developers <buildroot@buildroot.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"

# Linux kernel derived or related files
[[annotations]]
path = [
 "linux/*",
 "rootfs_overlay/usr/bin/config-pin"
]
precedence = "override"
SPDX-FileCopyrightText = "Various"
SPDX-License-Identifier = "GPL-2.0-only"

# U-Boot derived or related files
[[annotations]]
path = [
 "uboot/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2000-2013 Wolfgang Denk, DENX Software Engineering, wd@denx.de"
SPDX-License-Identifier = "GPL-2.0-or-later"

# Fwup config files
[[annotations]]
path = [
 "fwup-ops.conf",
 "fwup.conf",
 "fwup_include/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

# Various config files
[[annotations]]
path = [
 "busybox.fragment",
 "rootfs_overlay/etc/boardid.config",
 "rootfs_overlay/etc/erlinit.config",
 "rootfs_overlay/etc/fw_env.config",
 "rootfs_overlay/boot/extlinux/extlinux-a.conf",
 "rootfs_overlay/boot/extlinux/extlinux-b.conf"

]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

# https://mangopi.org/mqpro
[[annotations]]
path = [
 "assets/MangoPI_MQ_PRO_Pinout.svg",
 "assets/images/mq-pro-pink-t.png",
 "MangoPI_MQ_PRO_Pinout_source.excalidraw"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "MangoPi"
SPDX-License-Identifier = "CC-BY-SA-4.0"

